import os
import dotenv
from database import init_db
from graph import app

dotenv.load_dotenv()

def run_agent(query: str):
    print(f"\n" + "="*60)
    print(f"USER QUERY: {query}")
    print("="*60)
    
    initial_state = {
        "user_query": query,
        "schema_context": "",
        "generated_sql": "",
        "execution_error": None,
        "query_results": None,
        "retry_count": 0,
        "final_summary": ""
    }
    
    # Execute Graph
    final_state = app.invoke(initial_state)
    
    print(f"FINAL SQL: {final_state['generated_sql']}")
    print(f"RETRIES REQUIRED: {final_state['retry_count']}")
    if final_state['execution_error']:
        print(f"STATUS: FAILED ({final_state['execution_error']})")
    else:
        print(f"RAW RESULTS: {final_state['query_results']}")
        print("\n--- EXECUTIVE SUMMARY ---")
        print(final_state['final_summary'])
    print("="*60)

if __name__ == "__main__":
    # 1. Initialize SQLite sandbox
    init_db()
    
    # 2. Standard query testing aggregations and joins
    run_agent("What is the total completed revenue generated by Enterprise tier customers, broken down by region?")
    
    # 3. Intentional adversarial query to test self-healing (asking for a metric that requires joining and handling nulls/statuses)
    run_agent("Which customer has the highest ratio of failed or refunded transactions to completed transactions?") 